name: Release

on:
  push:
    branches:
      - release

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install

      # echo "//registry.npmjs.org/:_authToken=$ {{ secrets.NPM_TOKEN }}" > ~/.npmrc
      # git config --global user.email "actions@users.noreply.github.com"
      # git config --global user.name "GitHub Actions"
      - run: |
          unreleasedSection=$(awk '/## \[Unreleased\]/{flag=1; next} /## \[/{flag=0} flag' ./CHANGELOG.md | sed '/^[[:space:]]*$/d')
          if echo "$unreleasedSection" | grep -q '### Changed'; then
              pnpm version major
          elif echo "$unreleasedSection" | grep -q '### Added'; then
              pnpm version minor
          elif echo "$unreleasedSection" | grep -q '### Fixed'; then
              pnpm version patch
          fi

      - run: pnpm publish --access public

      - id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: "Release ${{ steps.get_tag.outputs.tag }}"
          body: "$unreleasedSection"
          draft: false
          prerelease: false
