# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      REPO_NAME: /${{ github.event.repository.name }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.local/share/pnpm/store/v3
          key: cache-pnpm-${{ hashFiles('./pnpn-lock.yaml') }}
          restore-keys: cache-pnpm-

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      # - name: Install dependencies
        # run: pnpm i

      - name: Build project
        run: pnpm start

      # Runs a single command using the runners shell
      - name: Repo name
        run: echo $REPO_NAME

      # Runs a single command using the runners shell
      - name: Is CI
        run: echo $CI
